[package]
name = "recipes"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = { workspace = true }
tokio = { workspace = true }
solana-zk-sdk = { workspace = true }
setup_participants = { path = "../ingredients/setup_participants" }
setup_mint = { path = "../ingredients/setup_mint" }
setup_token_account = { path = "../ingredients/setup_token_account" }
mint_tokens = { path = "../ingredients/mint_tokens" }
deposit_tokens = { path = "../ingredients/deposit_tokens" }
apply_pending_balance = { path = "../ingredients/apply_pending_balance" }
transfer = { path = "../ingredients/transfer" }
keypair_utils = { path = "../utils" }
withdraw_tokens = { path = "../ingredients/withdraw_tokens" }
global_auditor_assert = { path = "../ingredients/global_auditor_assert" }
setup_mint_confidential = { path = "../ingredients/setup_mint_confidential" }
