[package]
name = "keypair_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "2.0.1"
solana-sdk = "2.0.1"
solana-client = "2.0.1"
spl-token-client = "0.11.0"
spl-token-2022 = "4.0.0"
spl-associated-token-account = "4.0.0"
clap = "2.33.0"
solana-remote-wallet = {version = "2.0.1", features = ["hidapi"]}
solana-clap-utils = "2.0.1"


log = "0.4"
simple_logger = "5.0.0"

dotenv = "0.15.0" 
serde_json = "1.0.1"
tokio = { version = "1", features = ["full"] }