[package]
name = "keypair_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "2.1.2"
solana-sdk = "2.1.2"
solana-client = "2.1.2"
spl-token-client = { git = "https://github.com/solana-labs/solana-program-library" }
spl-token-2022 = { git = "https://github.com/solana-labs/solana-program-library" }
spl-associated-token-account = { git = "https://github.com/solana-labs/solana-program-library" }
spl-token-confidential-transfer-proof-extraction = { git = "https://github.com/solana-labs/solana-program-library" }
spl-token-confidential-transfer-proof-generation = { git = "https://github.com/solana-labs/solana-program-library" }
clap = "2.33.0"
solana-remote-wallet = {version = "2.0.1", features = ["hidapi"]}
solana-clap-utils = "2.0.1"

log = "0.4"
simple_logger = "5.0.0"

dotenv = "0.15.0" 
serde_json = "1.0.1"
tokio = { version = "1", features = ["full"] }